openapi: 3.0.3
info:
  title: 'Buy Together API Documentation'
  description: 'This API aims to provide all the information you need in order to work with our API'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/register:
    post:
      summary: 'User registration'
      operationId: userRegistration
      description: "This endpoint allows you to register a new user.\n<aside class=\"notice\">\nUsers will not be able to create or join purchase goals if they are not registered and logged in\n</aside>"
      parameters: []
      responses: {  }
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: wtqhogrnncfelbnjsghiys
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: jaunita.daugherty@example.org
                  nullable: true
                password:
                  type: string
                  description: ''
                  example: NQ(cVWF>S6^
                  nullable: false
                address:
                  type: string
                  description: ''
                  example: possimus
                  nullable: false
                phone_number:
                  type: string
                  description: ''
                  example: praesentium
                  nullable: false
                profile_pic:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 51200 kilobytes.'
                  nullable: true
              required:
                - name
                - password
                - address
                - phone_number
      security: []
  /api/login:
    post:
      summary: 'User authentication'
      operationId: userAuthentication
      description: "This endpoint allows authenticate or log in a user.\n<aside class=\"notice\">\nAn authentication token is always generated upon successful login.\n</aside>"
      parameters: []
      responses: {  }
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: betsy.reynolds@example.org
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: 'pu6Ia5I#s\'
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: 'User logout from application'
      operationId: userLogoutFromApplication
      description: "This endpoint allows you to logout a user from your app.\n<aside class=\"notice\">\nIt requires the auth token of the user to be logged out\n</aside>"
      parameters: []
      responses: {  }
      tags:
        - Authentication
      security: []
  '/api/purchase-goals/{id}/participants':
    get:
      summary: ''
      operationId: getApiPurchaseGoalsIdParticipants
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the purchase goal.'
        example: 17
        required: true
        schema:
          type: integer
  '/api/purchase-goals/{id}/join':
    post:
      summary: ''
      operationId: postApiPurchaseGoalsIdJoin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the purchase goal.'
        example: 16
        required: true
        schema:
          type: integer
  '/api/purchase-goals/{id}/approve/{user_id}':
    post:
      summary: ''
      operationId: postApiPurchaseGoalsIdApproveUser_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the purchase goal.'
        example: 18
        required: true
        schema:
          type: integer
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 12
        required: true
        schema:
          type: integer
  '/api/purchase-goals/{id}/decline/{user_id}':
    post:
      summary: ''
      operationId: postApiPurchaseGoalsIdDeclineUser_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the purchase goal.'
        example: 2
        required: true
        schema:
          type: integer
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 17
        required: true
        schema:
          type: integer
  '/api/purchase-goals/{id}/change-status':
    post:
      summary: 'Change the status of specified purchase goal'
      operationId: changeTheStatusOfSpecifiedPurchaseGoal
      description: "<aside class=\"notice\">\nOnly the owner of the goal can change its status from open to close and vice versa.\n</aside>"
      parameters: []
      responses: {  }
      tags:
        - 'Purchase Goals'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the purchase goal.'
        example: est
        required: true
        schema:
          type: string
  /api/purchase-goals:
    get:
      summary: 'Listing of all purchase goals.'
      operationId: listingOfAllPurchaseGoals
      description: "This endpoint allows users to view purchase goals.\n<aside class=\"notice\">\nUsers must NOT be authenticated to access this endpoint.\n</aside>"
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Purchase goals retrieved successfully.'
                  statusCode: 200
                  data: []
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Purchase goals retrieved successfully.'
                  statusCode:
                    type: integer
                    example: 200
                  data:
                    type: array
                    example: []
      tags:
        - 'Purchase Goals'
      security: []
    post:
      summary: 'Create a new purchase goal.'
      operationId: createANewPurchaseGoal
      description: "This endpoint allows users to create a purchase goal.\n<aside class=\"notice\">\nUsers must be authenticated to access this endpoint.\n</aside>"
      parameters: []
      responses: {  }
      tags:
        - 'Purchase Goals'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ohbjgfqrvdy
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Placeat aliquam provident reiciendis quia et.'
                  nullable: false
                target_amount:
                  type: number
                  description: 'Must be at least 0.'
                  example: 41
                  nullable: false
                amount_per_person:
                  type: number
                  description: 'Must be at least 0.'
                  example: 6
                  nullable: true
                product_name:
                  type: string
                  description: ''
                  example: aut
                  nullable: false
                product_description:
                  type: string
                  description: ''
                  example: est
                  nullable: false
                product_unit_price:
                  type: number
                  description: 'Must be at least 0.'
                  example: 71
                  nullable: false
                product_bulk_price:
                  type: number
                  description: 'Must be at least 0.'
                  example: 11
                  nullable: true
                product_quantity:
                  type: number
                  description: 'Must be at least 0.'
                  example: 14
                  nullable: false
                product_image:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 51200 kilobytes.'
                  nullable: true
                group_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vhqjapnjcbwbr
                  nullable: true
                start_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2025-01-21T10:59:00'
                  nullable: false
                end_date:
                  type: string
                  description: 'Must be a valid date. Must be a date after or equal to <code>start_date</code>.'
                  example: '2027-08-09'
                  nullable: true
              required:
                - title
                - description
                - target_amount
                - product_name
                - product_description
                - product_unit_price
                - product_quantity
                - start_date
      security: []
  '/api/purchase-goals/{id}':
    get:
      summary: 'Fetch details of a specific purchase goal.'
      operationId: fetchDetailsOfASpecificPurchaseGoal
      description: 'This endpoint allows users to view the details of a purchase goal by ID.'
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Purchase goal not found.'
                  statusCode: 404
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Purchase goal not found.'
                  statusCode:
                    type: integer
                    example: 404
      tags:
        - 'Purchase Goals'
      security: []
    put:
      summary: 'Update an existing purchase goal.'
      operationId: updateAnExistingPurchaseGoal
      description: "This endpoint allows users to update details of a purchase goal.\n<aside class=\"notice\">\nOnly the owner of the goal can update it.\n</aside>"
      parameters: []
      responses: {  }
      tags:
        - 'Purchase Goals'
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: rrtqjspiyrdradiwffclnb
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Aut amet a tempore porro magnam consequatur.'
                  nullable: false
                target_amount:
                  type: number
                  description: 'Must be at least 0.'
                  example: 28
                  nullable: false
                amount_per_person:
                  type: number
                  description: 'Must be at least 0.'
                  example: 59
                  nullable: true
                product_name:
                  type: string
                  description: ''
                  example: voluptate
                  nullable: false
                product_description:
                  type: string
                  description: ''
                  example: omnis
                  nullable: false
                product_unit_price:
                  type: number
                  description: 'Must be at least 0.'
                  example: 51
                  nullable: false
                product_bulk_price:
                  type: number
                  description: 'Must be at least 0.'
                  example: 14
                  nullable: true
                product_quantity:
                  type: number
                  description: 'Must be at least 0.'
                  example: 23
                  nullable: false
                product_image:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 51200 kilobytes.'
                  nullable: true
                group_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: qad
                  nullable: true
                start_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2025-01-21T10:59:00'
                  nullable: false
                end_date:
                  type: string
                  description: 'Must be a valid date. Must be a date after or equal to <code>start_date</code>.'
                  example: '2121-06-05'
                  nullable: true
      security: []
    delete:
      summary: 'Delete a purchase goal.'
      operationId: deleteAPurchaseGoal
      description: "This endpoint allows users to delete a specific purchase goal by ID.\n<aside class=\"notice\">\nOnly the owner of the goal can delete it.\n</aside>"
      parameters: []
      responses: {  }
      tags:
        - 'Purchase Goals'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the purchase goal.'
        example: 18
        required: true
        schema:
          type: integer
tags:
  -
    name: Authentication
    description: 'Endpoints for login, registration, and logout'
  -
    name: Endpoints
    description: ''
  -
    name: 'Purchase Goals'
    description: 'Endpoints for managing purchase goals'
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
