openapi: 3.0.3
info:
  title: 'Buy Together API Documentation'
  description: 'This API aims to provide all the information you need in order to work with our API'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/register:
    post:
      summary: 'User registration'
      operationId: userRegistration
      description: "This endpoint allows you to register a new user.\n<aside class=\"notice\">\nUsers will not be able to create or join purchase goals if they are not registered and logged in\n</aside>"
      parameters: []
      responses: {  }
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: qohsesjhpekjknvtxpgbqfeq
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: atillman@example.net
                  nullable: true
                password:
                  type: string
                  description: ''
                  example: jcxJZ!A
                  nullable: false
                password_confirmation:
                  type: string
                  description: ''
                  example: jcxJZ!A
                  nullable: false
                address:
                  type: string
                  description: ''
                  example: praesentium
                  nullable: false
                phone_number:
                  type: string
                  description: ''
                  example: illum
                  nullable: false
                profile_pic:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 51200 kilobytes.'
                  nullable: true
              required:
                - name
                - password
                - password_confirmation
                - address
                - phone_number
      security: []
  /api/login:
    post:
      summary: 'User authentication'
      operationId: userAuthentication
      description: "This endpoint allows authenticate or log in a user.\n<aside class=\"notice\">\nAn authentication token is always generated upon successful login.\n</aside>"
      parameters: []
      responses: {  }
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: ian76@example.org
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: '{_aV!Uh]"nUgRH'
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: 'User logout from application'
      operationId: userLogoutFromApplication
      description: "This endpoint allows you to logout a user from your app.\n<aside class=\"notice\">\nIt requires the auth token of the user to be logged out\n</aside>"
      parameters: []
      responses: {  }
      tags:
        - Authentication
      security: []
  '/api/purchase-goals/{purchase_goal}/change-status':
    post:
      summary: 'Change the status of specified purchase goal'
      operationId: changeTheStatusOfSpecifiedPurchaseGoal
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: purchase_goal
        description: ''
        example: consequatur
        required: true
        schema:
          type: string
  /api/purchase-goals:
    get:
      summary: 'Display a listing of the purchase goals.'
      operationId: displayAListingOfThePurchaseGoals
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created purchase goal in storage.'
      operationId: storeANewlyCreatedPurchaseGoalInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: uehglakbwbbttkjuqbshcxk
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Possimus eos sint et quia voluptas distinctio impedit.'
                  nullable: false
                target_amount:
                  type: number
                  description: 'Must be at least 0.'
                  example: 60
                  nullable: false
                amount_per_person:
                  type: number
                  description: 'Must be at least 0.'
                  example: 83
                  nullable: true
                product_name:
                  type: string
                  description: ''
                  example: odit
                  nullable: false
                product_description:
                  type: string
                  description: ''
                  example: dignissimos
                  nullable: false
                product_unit_price:
                  type: number
                  description: 'Must be at least 0.'
                  example: 16
                  nullable: false
                product_bulk_price:
                  type: number
                  description: 'Must be at least 0.'
                  example: 45
                  nullable: true
                product_quantity:
                  type: number
                  description: 'Must be at least 0.'
                  example: 25
                  nullable: false
                product_image:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 51200 kilobytes.'
                  nullable: true
                group_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: dzlsgnvxqx
                  nullable: true
                start_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2025-01-21T05:30:20'
                  nullable: false
                end_date:
                  type: string
                  description: 'Must be a valid date. Must be a date after or equal to <code>start_date</code>.'
                  example: '2052-09-25'
                  nullable: true
              required:
                - title
                - description
                - target_amount
                - product_name
                - product_description
                - product_unit_price
                - product_quantity
                - start_date
      security: []
  '/api/purchase-goals/{id}':
    get:
      summary: 'Display the specified purchase goal.'
      operationId: displayTheSpecifiedPurchaseGoal
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified purchase goal in storage.'
      operationId: updateTheSpecifiedPurchaseGoalInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: xayinqiombdrygwhxrhb
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Necessitatibus neque quibusdam vel.'
                  nullable: false
                target_amount:
                  type: number
                  description: 'Must be at least 0.'
                  example: 82
                  nullable: false
                amount_per_person:
                  type: number
                  description: 'Must be at least 0.'
                  example: 13
                  nullable: true
                product_name:
                  type: string
                  description: ''
                  example: optio
                  nullable: false
                product_description:
                  type: string
                  description: ''
                  example: minima
                  nullable: false
                product_unit_price:
                  type: number
                  description: 'Must be at least 0.'
                  example: 28
                  nullable: false
                product_bulk_price:
                  type: number
                  description: 'Must be at least 0.'
                  example: 67
                  nullable: true
                product_quantity:
                  type: number
                  description: 'Must be at least 0.'
                  example: 58
                  nullable: false
                product_image:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 51200 kilobytes.'
                  nullable: true
                group_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: a
                  nullable: true
                start_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2025-01-21T05:30:20'
                  nullable: false
                end_date:
                  type: string
                  description: 'Must be a valid date. Must be a date after or equal to <code>start_date</code>.'
                  example: '2081-07-02'
                  nullable: true
      security: []
    delete:
      summary: 'Remove the specified purchase goal from storage.'
      operationId: removeTheSpecifiedPurchaseGoalFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the purchase goal.'
        example: fugit
        required: true
        schema:
          type: string
  '/api/purchase-goals/{purchase_goal}/participants':
    get:
      summary: ''
      operationId: getApiPurchaseGoalsPurchase_goalParticipants
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: purchase_goal
        description: ''
        example: id
        required: true
        schema:
          type: string
  '/api/purchase-goals/{purchase_goal}/join':
    post:
      summary: ''
      operationId: postApiPurchaseGoalsPurchase_goalJoin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: purchase_goal
        description: ''
        example: dolor
        required: true
        schema:
          type: string
  '/api/purchase-goals/{purchase_goal_id}/approve/{user_id}':
    post:
      summary: ''
      operationId: postApiPurchaseGoalsPurchase_goal_idApproveUser_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: purchase_goal_id
        description: 'The ID of the purchase goal.'
        example: 7
        required: true
        schema:
          type: integer
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 12
        required: true
        schema:
          type: integer
  '/api/purchase-goals/{purchase_goal_id}/decline/{user_id}':
    post:
      summary: ''
      operationId: postApiPurchaseGoalsPurchase_goal_idDeclineUser_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: purchase_goal_id
        description: 'The ID of the purchase goal.'
        example: 20
        required: true
        schema:
          type: integer
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 2
        required: true
        schema:
          type: integer
  /api/products:
    post:
      summary: ''
      operationId: postApiProducts
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/products/{id}':
    put:
      summary: ''
      operationId: putApiProductsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiProductsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 9
        required: true
        schema:
          type: integer
tags:
  -
    name: Authentication
    description: 'Endpoints for login, registration, and logout'
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
